apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
    spec:
      hostNetwork: true
      containers:
      - name: kube-proxy
        image: registry.k8s.io/kube-proxy:v1.28.0
        command:
          - /usr/local/bin/kube-proxy
          - --config=/var/lib/kube-proxy/config.conf
        volumeMounts:
          - name: kube-proxy-config
            mountPath: /var/lib/kube-proxy
        securityContext:
          privileged: true
      volumes:
        - name: kube-proxy-config
          projected:
            sources:
              - configMap:
                  name: kube-proxy
                  items:
                    - key: config.conf
                      path: config.conf
              - configMap:
                  name: kube-proxy-kubeconfig
                  items:
                    - key: kubeconfig.conf
                      path: kubeconfig.conf
